version: "3.1"
services:
  job_board_db:
    image: postgres
    container_name: job_board_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: job_board
    volumes:
      - job_board_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  job_board_adminer:
    image: adminer
    container_name: job_board_adminer
    restart: always
    ports:
      - 8080:8080

  job_board_redis:
    image: redislabs/redismod
    container_name: job_board_redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

  job_board_redisinsight:
    image: oblakstudio/redisinsight
    container_name: job_board_redisinsight
    restart: always
    ports:
      - "8006:5000"
    volumes:
      - redis_db:/db

volumes:
  job_board_data:
  redis_db:
